# Generated by Django 3.0.3 on 2020-03-24 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('secure_code', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(unique=True)),
                ('account_type', models.CharField(max_length=50)),
                ('account_balance', models.DecimalField(decimal_places=5, max_digits=30)),
                ('isLocked', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bankingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19, unique=True)),
                ('cvc', models.IntegerField()),
                ('expiration_date', models.DateField(verbose_name='DATE')),
                ('isDisabled', models.BooleanField(default=False)),
                ('cardType', models.CharField(choices=[('ST', 'Standard'), ('SC', 'Student Credit'), ('CC', 'Charge Cards'), ('SECC', 'Secured Credit'), ('PR', 'Prepaid')], default='ST', max_length=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creditcard', to='banking.account')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='DATE')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=30)),
                ('balance', models.DecimalField(decimal_places=5, max_digits=30)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sender', to='banking.account')),
                ('creditcard_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditcard_used', to='banking.bankingCard')),
                ('receiver_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_receiver', to='banking.account')),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date', models.DateField(verbose_name='DATE')),
                ('status', models.CharField(max_length=50)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='banking.account')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='banking.account')),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='DATE')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_users', to='banking.account')),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifation_id', to='banking.notifications')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='banking.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_amount', models.DecimalField(decimal_places=5, max_digits=30)),
                ('interest', models.IntegerField()),
                ('loan_date', models.DateField(verbose_name='DATE')),
                ('due_date', models.DateField(verbose_name='DATE')),
                ('balance', models.DecimalField(decimal_places=5, max_digits=30)),
                ('isPaid', models.BooleanField(default=False)),
                ('numberOfPayments', models.IntegerField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaner', to='banking.account')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_id', to='banking.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('barrangay', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bankCryptographyKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('keyName', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userKey', to='banking.account')),
            ],
        ),
    ]
