# Generated by Django 3.0.3 on 2020-03-24 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_apitransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='api_key',
            field=models.CharField(default='BvWLqjET', max_length=50),
            preserve_default=False,
        ),
    ]
