# Generated by Django 3.0.3 on 2020-03-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_account_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankingcard',
            old_name='cvc',
            new_name='cvv',
        ),
        migrations.CreateModel(
            name='unconfirmedPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Charge', models.CharField(max_length=50)),
                ('pending', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=30)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='DATE')),
                ('dateConfirmed', models.DateTimeField(blank=True, verbose_name='DATE')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='banking.account')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='banking.account')),
            ],
        ),
    ]
