# Generated by Django 3.0.3 on 2020-03-27 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_auto_20200327_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitransaction',
            name='parentTransaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_transaction', to='banking.ApiPayments'),
        ),
    ]
