# Generated by Django 3.0.3 on 2020-03-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_auto_20200327_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='apipayments',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
