# Generated by Django 3.0.3 on 2020-03-27 09:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_apipayments_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledpayments',
            name='transaction',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={
    "Msg": "Payment has been saved. Waiting confirmation from the user",
    "status": True,
    "requestId": 25,
    "date": "2020-03-27 17:16:22.612578",
    "amount": 1000.0,
    "invoice_id": "1",
    "confirmed": False,
    "links": [
        {
            "href": "http://192.168.1.6:8888/api/payments/sale/25",
            "rel": "self",
            "method": "GET"
        },
        {
            "href": "http://192.168.1.6:8888/api/payments/sale/25/refund",
            "rel": "refund",
            "method": "POST"
        },
        {
            "href": "http://192.168.1.6:8888/api/payments/sale/25/cancel",
            "rel": "cancel",
            "method": "POST"
        }
    ]
}),
            preserve_default=False,
        ),
    ]
