# Generated by Django 3.0.3 on 2020-03-30 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_cancelledpayments_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='DATE')),
                ('subject', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('opened', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='sender_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='balance',
            new_name='newBalance',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='transacOwner',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver_account_id',
            new_name='transacReceiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='creditcard_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='DATE'),
        ),
        migrations.DeleteModel(
            name='logs',
        ),
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
