# Generated by Django 3.0.3 on 2020-03-30 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_auto_20200330_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
