# Generated by Django 3.0.4 on 2020-06-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_auto_20200330_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='DATE')),
            ],
        ),
        migrations.AlterModelOptions(
            name='emails',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
    ]
