# Generated by Django 3.0.4 on 2020-06-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0014_auto_20200609_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='accountNumber',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
