# Generated by Django 3.0.4 on 2020-06-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0016_auto_20200615_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='receiver',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
