# Generated by Django 3.0.4 on 2020-06-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0017_auto_20200615_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='action',
            new_name='eventname',
        ),
    ]
